services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: psqlx
      POSTGRES_PASSWORD: psqlx
      PGDATA: /data/postgres
      POSTGRES_DB: uploads
    ports:
      - "5432:5432"
    restart: unless-stopped


  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
  
  
  backend-etl:
    image: backend-etl
    container_name: backend-etl
    ports:
      - "8888:8888"
    volumes:
      - /server_data:/server_data
      - /metadata:/metadata
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    restart: unless-stopped



    
networks:
  db:
    driver: bridge
  
volumes:
  redis_data:
    driver: local

    
# sudo docker exec -it <id> psql  -U psqlx -d uploads
